name: Release to PyPI

on:
  pull_request:
    types:
      - closed

jobs:
  build-n-publish:
    # ChatGPT suggestion 1
    # if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release-please')

    # ChatGPT suggestion 2
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release-please')
    # if: github.event.pull_request.merged == true
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Install dependencies
        run: |
          poetry install
          pip install wheel setuptools

      - name: Build package
        run: make package

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
