on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check tag prefix
      if: startsWith(env.GITHUB_REF, 'refs/tags/v')
      run: |
        echo "Valid tag: ${{ env.GITHUB_REF }}"
    - name: Report error
      if: not(startsWith(env.GITHUB_REF, 'refs/tags/v'))
      run: |
        echo "Invalid tag: ${{ env.GITHUB_REF }}"
        exit 1
