name: trig-on-release

on:
  release:

permissions:
  contents: read

jobs:
  trig-on-release:
    runs-on: ubuntu-latest

    steps:
    - name: Echo current activity name
      run: |
        echo "Current activity type: ${{ github.event_name }}"

    - name: Echo github object
      run: |
        echo "'${{ toJson(github) }}'"
